### ISSUE TITLE
Fail to compile (gulp build)

### ISSUE THREAD

**Issue by namibian15** [igalarza/dhtmlx-e6#1]
Hi,
I just cloned you project. Thanks for making it available. However, I am getting an error when trying to compile with "gulp build". 
![gulp-issue for dhtml-es6-master](https://user-images.githubusercontent.com/14940661/32110604-eb047ffa-bb05-11e7-9c2b-a95eb1a0ae39.png)

I am using node version 6.11.5, npm version 3.10.10, gulp-cli version 1.4.0 and gulp local version 3.9.1

Thanks!

**Comment by igalarza** [comment]
Hi! The project was created with an older version of rollup, they changed some configuration parameters that broke backwards compatibility.

I've just fixed it and commited the changes, let me know if it works now.

You're welcome!

**Comment by namibian15** [comment]
Awesome! Thanks for the quick response. It is working smoothly and I am able to test out DHTMLX Grid functionality.

**Comment by igalarza** [comment]
Seems to be working! Fixed in commit #6a4c0f5

Thanks for your contribution.
